ADSProject/Models/GruposViewModel.cs
using ADSProject.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ADSProyect.Models
{
    public class GruposViewModel
    {
        [Display(Name = "ID Grupo")]
        [Key]
        public int idGrupo { get; set; }


        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [Display(Name = "ID Carrera")]
        public int idCarrera { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [Display(Name = "ID Materia")]
        public int idMateria { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [Display(Name = "ID Profesor")]
        public int idProfesor { get; set; }
     
        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [Display(Name = "Ciclo")]
        public int ciclo { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [Display(Name = "Año")]
        public int anio { get; set; }

        public bool estado { get; set;  }
    }
}

ADSProject/Controllers/GrupoController.cs
using ADSProject.Utils;
using ADSProyect.Models;
using ADSProyect.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADSProyect.Controllers
{
    public class GrupoController : Controller
    {
        private readonly IGrupoRepository grupoRepository;

        public GrupoController(IGrupoRepository grupoRepository)
        {
            this.grupoRepository = grupoRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var item = grupoRepository.obtenerGrupos();

                return View(item);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public IActionResult Form(int? idGrupo, Operaciones operaciones)
        {
            try
            {
                var Grupo = new GruposViewModel();

                if (idGrupo.HasValue)
                {
                    Grupo = grupoRepository.obtenerGruposPorID(idGrupo.Value);
                }
                // Indica el tipo de operacion que es esta realizando
                ViewData["Operaciones"] = operaciones;

                return View(Grupo);

            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Form(GruposViewModel gruposViewModel)
        {
            try
            {
                if (gruposViewModel.idGrupo == 0) // En caso de insertar
                {
                    grupoRepository.agregarGrupo(gruposViewModel);
                }
                else // En caso de actualizar
                {
                    grupoRepository.actualizarGrupo
                        (gruposViewModel.idGrupo, gruposViewModel);
                }

                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Delete(int idGrupo)
        {
            try
            {
                grupoRepository.eliminarGrupo(idGrupo);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }
    }
}

ADSProject/Views/Grupo/Form.cshtml
@model ADSProyect.Models.GruposViewModel

@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Form</h1>

<h4>Grupos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <input type="hidden" id="operacion" value="@ViewData["Operaciones"]" />
        <input type="hidden" id="_redirectURL" value="@Url.Action("Index" , "Grupo")" />
        <form asp-action="Form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                
                <input asp-for="idGrupo" class="form-control" type ="hidden"/>
                
            </div>
            <div class="form-group">
                <label asp-for="idCarrera" class="control-label"></label>
                <input asp-for="idCarrera" class="form-control" />
                <span asp-validation-for="idCarrera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idMateria" class="control-label"></label>
                <input asp-for="idMateria" class="form-control" />
                <span asp-validation-for="idMateria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idProfesor" class="control-label"></label>
                <input asp-for="idProfesor" class="form-control" />
                <span asp-validation-for="idProfesor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ciclo" class="control-label"></label>
                <input asp-for="ciclo" class="form-control" />
                <span asp-validation-for="ciclo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="anio" class="control-label"></label>
                <input asp-for="anio" class="form-control" />
                <span asp-validation-for="anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>$(document).ready(function () {
        // Cuando la operacion sobre el formulario es de lectura.
        if ($("#operacion").val() == "leer") {
            $("form").find("input,select").attr("disabled", true);
        }
    });
    //Agregando ajax
    $("form").addClass("form-ajax");
    //activando ajax
    initAjaxForm();</script>
}

ADSProject/Views/Grupo/Index.cshtml
@model IEnumerable<ADSProyect.Models.GruposViewModel>
  @using ADSProject.Utils
    @{
        ViewData["Title"] = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <div class="container">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Estudiantes</h3>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-success d-block" asp-action="Form"
                       asp-route-operaciones="@Operaciones.agregar">Agregar Grupo</a>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.idGrupo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.idCarrera)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.idMateria)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ciclo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.anio)
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idGrupo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idCarrera)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idMateria)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ciclo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.anio)
                                </td>
                                <td>
                                    <a class="btn btn-primary"
                                       asp-route-idGrupo="@item.idGrupo"
                                       asp-action="Form"
                                       asp-route-operaciones="@Operaciones.modificar">Modificar</a>
                                    <a class="btn btn-warning"
                                       asp-route-idGrupo="@item.idGrupo"
                                       asp-action="Form"
                                       asp-route-operaciones="@Operaciones.leer">Leer</a>
                                    <a class="btn btn-danger eliminar"
                                       asp-route-idGrupo="@item.idGrupo"
                                       asp-action="Delete">Eliminar</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table> }
            else
            {
                <h3 class="text-center">Lista vacia.</h3>}
        </div>
    </div>