ADSProject/Controllers/ProfesorController.cs
using ADSProject.Utils;
using ADSProyect.Models;
using ADSProyect.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADSProyect.Controllers
{
    public class ProfesorController : Controller
    {
        private readonly IProfesorRepository profesorRepository;
        public ProfesorController(IProfesorRepository profesorRepository)
        {
            this.profesorRepository = profesorRepository;
        }


        [HttpGet]
        public IActionResult Index()
        {
             try
            {
                var item =profesorRepository.obtenerProfesores();

                return View(item);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public IActionResult Form(int? idProfesor, Operaciones operaciones)
        {
            try
            {
                var profesor = new ProfesoresViewModel();

                if (idProfesor.HasValue)
                {
                    profesor = profesorRepository.obtenerProfesorPorID(idProfesor.Value);
                }
                // Indica el tipo de operacion que es esta realizando
                ViewData["Operaciones"] = operaciones;

                return View(profesor);

            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Form(ProfesoresViewModel profesoresViewModel)
        {
            try
            {
                if (profesoresViewModel.idProfesor == 0) // En caso de insertar
                {
                    profesorRepository.agregarProfesor(profesoresViewModel);
                }
                else // En caso de actualizar
                {
                    profesorRepository.actualizarProfesor
                        (profesoresViewModel.idProfesor, profesoresViewModel);
                }

                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Delete(int idProfesor)
        {
            try
            {
                profesorRepository.eliminarProfesor(idProfesor);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }
    }
}

ADSProject/Views/Profesor/Form.cshtml
@model ADSProyect.Models.ProfesoresViewModel

@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Form</h1>

<h4>Profesores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Form">
            <input type="hidden" id="operacion" value="@ViewData["Operaciones"]" />
            <input type="hidden" id="_redirectURL" value="@Url.Action("Index" , "Profesor")" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <input asp-for="idProfesor" class="form-control" type="hidden" />

            </div>
            <div class="form-group">
                <label asp-for="nombreProfesor" class="control-label"></label>
                <input asp-for="nombreProfesor" class="form-control" />
                <span asp-validation-for="nombreProfesor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidoProfesor" class="control-label"></label>
                <input asp-for="apellidoProfesor" class="form-control" />
                <span asp-validation-for="apellidoProfesor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correoProfesor" class="control-label"></label>
                <input asp-for="correoProfesor" class="form-control" />
                <span asp-validation-for="correoProfesor" class="text-danger"></span>
            </div>
            <input type="checkbox" asp-for="estado" value="true" type="hidden" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>$(document).ready(function () {
        // Cuando la operacion sobre el formulario es de lectura.
        if ($("#operacion").val() == "leer") {
            $("form").find("input,select").attr("disabled", true);
        }
});

    //Agregando ajax
    $("form").addClass("form-ajax");
    //activando ajax
    initAjaxForm();
    </script>
}

ADSProject/Views/Profesor/Index.cshtml
@model IEnumerable<ADSProyect.Models.ProfesoresViewModel>
@using ADSProject.Utils
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6">
                <h3>Profesores</h3>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-success d-block" asp-action="Form"
                   asp-route-operaciones="@Operaciones.agregar">Agregar Materia</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.idProfesor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nombreProfesor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.apellidoProfesor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.correoProfesor)
                        </th>

                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.idProfesor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombreProfesor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.apellidoProfesor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.correoProfesor)
                        </td>

                        <td>
                            <a class="btn btn-primary"
                               asp-route-idProfesor="@item.idProfesor"
                               asp-action="Form"
                               asp-route-operaciones="@Operaciones.modificar">Modificar</a>
                            <a class="btn btn-warning"
                               asp-route-idProfesor="@item.idProfesor"
                               asp-action="Form"
                               asp-route-operaciones="@Operaciones.leer">Leer</a>
                            <a class="btn btn-danger eliminar"
                               asp-route-idProfesor="@item.idProfesor"
                               asp-action="Delete">Eliminar</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table> }
        else
        {
            <h3 class="text-center">Lista vacia.</h3>}
    </div>
</div>